Web/Controllers/AssetsController.cs
using BankManagementSystem.Models.Enum;
using System.Threading.Tasks;
using BankManagementSystem.Common.BindingModels.Asset;
using BankManagementSystem.Common.Constants;
using BankManagementSystem.Common.Helpers;
using BankManagementSystem.Common.ViewModels.Asset;
using BankManagementSystem.Models;
using BankManagementSystem.Services.DataServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BankManagementSystem.Web.Controllers
{
    [Authorize]
    public class AssetsController : Controller
    {

        private IAssetService assetService;
        UserManager<Client> userManager;

        public AssetsController(IAssetService assetService,
            UserManager<Client> userManager)
        {
            this.assetService = assetService;
            this.userManager = userManager;
        }

        [Authorize(Roles = RolesConstants.Administrator)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAssetBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.assetService.Create(model, this.User.Identity.Name);

            return this.RedirectToAction(ActionConstants.Index, ControllerConstants.Assets);
        }

        public async Task<IActionResult> Index()
        {
            var assets = (await this.assetService.GetAllAssetsAsync());
            return View(assets);
        }

        [HttpGet]
        public async Task<IActionResult> Purchase(int id, PurchaseAssetDto DTO)
        {
            await this.PopulateDTOAsync(DTO, id);
            return View(DTO);
        }

        [HttpPost("Assets/Purchase/{id:int}")]
        public async Task<IActionResult> PurchaseConfirm(int id, PurchaseAssetDto DTO)
        {
            if (!this.ModelState.IsValid)
            {
                await this.PopulateDTOAsync(DTO, id);
                return this.View(ViewNameConstants.Purchase, DTO);
            }

            await this.assetService.PurchaseAssetAsync(DTO.BindingModel, this.User.Identity.Name);

            string clientId = await ClientHelper.
                GetUserIdAsync(this.User.Identity.Name, this.userManager);
            
            return this.RedirectToAction(ActionConstants.Success, ControllerConstants.Assets);
        }

        public IActionResult Success()
        {
            return View();
        }

        private async Task<PurchaseAssetDto> PopulateDTOAsync(PurchaseAssetDto DTO, int id)
        {
            var viewModel = await this.assetService.FindById(id);
            DTO.ViewModel = viewModel;
            DTO.CurrentClientBalance = 
                await ClientHelper.GetUserBalance(this.User.Identity.Name, this.userManager);
            return DTO;
        }
    }
}

Web/Controllers/CreditCardsController.cs
namespace BankManagementSystem.Web.Controllers
{
    using BankManagementSystem.Common.BindingModels.CreditCard;
    using BankManagementSystem.Common.Constants;
    using BankManagementSystem.Common.Helpers;
    using BankManagementSystem.Models;
    using BankManagementSystem.Services.DataServices;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using System.Threading.Tasks;

    [Authorize]
    public class CreditCardsController : Controller
    {
        private ICreditCardService creditCardService;
        private UserManager<Client> userManager;

        public CreditCardsController(ICreditCardService creditCardService, UserManager<Client> userManager)
        {
            this.creditCardService = creditCardService;
            this.userManager = userManager;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCreditCardBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.creditCardService.Create(model, this.User.Identity.Name);
            
            return this.RedirectToAction(ActionConstants.Index, ControllerConstants.CreditCards);
        }

        public async Task<IActionResult> Index()
        {
            string clientId = await ClientHelper.GetUserIdAsync(this.User.Identity.Name, this.userManager);
            var creditCards = await this.creditCardService.GetAllCreditCardsAsync(clientId);
            return View(creditCards);
        }
    }
}

Web/Views/Shared/_AdministratorPartial.cshtml
@if (User.IsInRole(RolesConstants.Administrator))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="Create">
            <button class="btn btn-sm btn-warning">Create Asset</button>
        </a>
    </li>
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankManagementSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-light">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Credit Cards
                        </a>
                        <div class="dropdown-menu" aria-labelledby="customersDropdown">
                            <a class="dropdown-item" asp-controller="CreditCards" asp-action="Index">My Cards</a>
                            <a class="dropdown-item" asp-controller="CreditCards" asp-action="Create">Create Card</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="@PageConstants.DepositCreate">Deposit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="@PageConstants.WithdrawIndex">Withdraw</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Assets" asp-action="Index">Assets</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Credit
                        </a>
                        <div class="dropdown-menu" aria-labelledby="customersDropdown">
                            <a class="dropdown-item" asp-page="@PageConstants.CreditIndex">Credit table</a>
                            <a class="dropdown-item" asp-page="@PageConstants.CreditCreate">Create Credit</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="@PageConstants.TransactionIndex">Transactions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <partial name="_AdministratorPartial" />
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </nav>
    </header>
    <div class="main">
        <partial name="_CookieConsentPartial" />
        @RenderBody()
    </div>

    <footer class="page-footer font-small text-white border-top text-dark">        
        <div class="footer-copyright text-center py-3">
            © 2021 Copyright:
            <a href="/">George Bank</a>
        </div>
    </footer>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>